name: Tourism Project Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch
  workflow_dispatch:  # Allows manual runs from the Actions tab

permissions:
  contents: write

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pandas
      - name: Register Dataset
        run: python tourism_project/model_building/data_register.py
      - name: Upload Registered Dataset
        uses: actions/upload-artifact@v4
        with:
          name: registered-data
          path: tourism_project/data/tourism.csv

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pandas scikit-learn joblib
      - name: Run Data Preparation
        run: python tourism_project/model_building/prep.py
      - name: Upload Data Splits and Preprocessor
        uses: actions/upload-artifact@v4
        with:
          name: data-splits
          path: |
            Xtrain.csv
            Xtest.csv
            ytrain.csv
            ytest.csv
            tourism_project/deployment/preprocessor.joblib

  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install pandas scikit-learn xgboost joblib mlflow
      - name: Download Data Splits and Preprocessor
        uses: actions/download-artifact@v4
        with:
          name: data-splits
      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &
          sleep 5  # Wait for server startup
      - name: Model Building
        run: python tourism_project/model_building/train.py
      - name: Commit Trained Model and Preprocessor
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f tourism_project/deployment/Wellness_Tourism_Predictor_model_v1.joblib
          git add -f tourism_project/deployment/preprocessor.joblib
          git commit -m "Update model and preprocessor artifacts [skip ci]" || echo "No changes to commit"
          git push
